# Generated by Django 3.0.4 on 2020-04-30 07:56

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Clow',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('sign', models.CharField(max_length=100)),
                ('description', models.TextField(max_length=250)),
                ('magic', models.CharField(max_length=100)),
            ],
        ),
    ]
